name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    name: "Tests [${{ matrix.os }}]"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        id: setup-ruby
        with:
          ruby-version: 2.6.6
          bundler: none
      - uses: eregon/clean-path@v1
        with:
          regexp: '\bruby\b'
      - name: Install dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y ruby zsh shunit2
        if: ${{ runner.os == 'Linux' }}
      - name: Install dependencies
        run: brew install shunit2
        if: ${{ runner.os == 'macOS' }}
      - name: Configure env
        run: |
          echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
          echo "SETUP_RUBY_PREFIX=${{ steps.setup-ruby.outputs.ruby-prefix }}" >> $GITHUB_ENV
      - name: Run tests
        run: make test
